name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Ensure the version matches your project requirement

      - name: Install dependencies
        run: yarn install # Use yarn to install dependencies

      - name: Build the project
        run: yarn build # Build the Next.js project

      - name: Deploy to Vercel
        run: |
          yarn global add vercel
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
